version: "3"
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: vladrezdev/cyclecyclecycle
    volumes:
      - ".:/usr/src/app"
      - ".:/usr/src/app/node_modules"
      ports: 
        - "2222:5000"
      environment:
        -NODE_ENV=production
