module.exports = ['Chewyplay',
'Useful January',
'B.O.X.',
'The Useful Spacemen\'s Club',
'Lisa Talent',
'Jupiter Revival',
'Puppiesica',
'Lisa Eats the Box',
'Lisaatron',
'One Girl, Ten Cats',
'Lisa\'s Useful Box',
'No Box',
'The Useful Cats',
'The Working Cats',
'The Chewy Heroes of Jupiter',
'The Box Puppies',
'Working Twins',
'The Working Chewy Spacemen',
'Jupiter Thunder Teeth',
'Box Ten',
'Ten Working Iced Puppies',
'The Love of Cats',
'Das Box',
'Beyond Jupiter',
'Twilight of the Box Gods',
'Chewy Cats of the Green Box',
'This Box',
'Riot of the Green Box',
'Flight of the Cats',
'Working in Jupiter',
'Why Puppies, Why?',
'Few Jude',
'Insignificant Jude',
'Bitty Jude',
'Dwarfish Jude',
'Immature Jude',
'Jude the Diminutive',
'Bittie Jude',
'Microscopic Jude',
'Jude the Brief',
'Jude the Big',
'Jude the Calmly',
'Gentle Jude',
'Jude the Calmness',
'Inconspicuous Jude',
'Impassive Jude',
'Discreet Jude',
'Jude the Comfortable',
'Loud Jude',
'Jude the Calm',
'Catlike Jude',
'Detestable Jude',
'Jude the Gummy',
'Cloying Jude',
'Jude the Rance',
'Disgusting Jude',
'Jude the Corrosive',
'Ambrosial Jude',
'Rancid Jude',
'Filthy Jude',
'Jude the Salty',
'Scotland Panic',
'Fairyhead',
'The Daring Balloons',
'One Zilliondust',
'Purely Ginger',
'Crazyknot',
'Taking Back October',
'One Zillion Seconds to Scotland',
'The Daring Brains',
'Crazy Fairy Cult',
'Crazy Tooth',
'Bathtub Daring',
'The Crazy Perry Project',
'Fairy One Zillion',
'Disciples Of Scotland',
'Daring Dolls',
'Crazy Crazy Crazy',
'The Crazy Brothers',
'Perry and the Bumpy Humans',
'Letters From Perry of the Elephants',
'Das Fairy',
'Twilight of the Fairy Gods',
'Au Revior Brains']