module.exports = ['Chewyplay',
'Useful January',
'B.O.X.',
'The Useful Spacemen\'s Club',
'Lisa Talent',
'Jupiter Revival',
'Puppiesica',
'Lisa Eats the Box',
'Lisaatron',
'One Girl, Ten Cats',
'Lisa\'s Useful Box',
'No Box',
'The Useful Cats',
'The Working Cats',
'The Chewy Heroes of Jupiter',
'The Box Puppies',
'Working Twins',
'The Working Chewy Spacemen',
'Jupiter Thunder Teeth',
'Box Ten',
'Ten Working Iced Puppies',
'The Love of Cats',
'Das Box',
'Beyond Jupiter',
'Twilight of the Box Gods',
'Chewy Cats of the Green Box',
'This Box',
'Riot of the Green Box',
'Flight of the Cats',
'Working in Jupiter',
'Why Puppies, Why?',
'Few Frank Moss',
'Insignificant Ruby Canmore',
'Bitty John Mai',
'Dwarfish William Mccray',
'Immature Jude',
'Mr Robyn Upreti the Diminutive',
'Bittie Prof Amelia',
'Microscopic Keanu and Anakoni',
'Joseph Maki the Brief',
'James Mohamed the Big',
'Master George Maloney the Calmly',
'Gentle Prof Anna Carrow',
'Mr Regan Malakar the Calmness',
'Inconspicuous Master William Mccray',
'Impassive Hannah Crowfeather',
'Discreet Mr Ruben Sadangi',
'Robert Milne the Comfortable',
'Loud Prof Anna Carrow',
'Mr Ron Maji the Calm',
'Catlike Jude',
'Bring Me the Balloons',
'Flight of the Blond Gerbils',
'Cloying Map Failure',
'Map, Balloons and Gerbils',
'Disgusting Megamap',
'Prof Ella Crow the Corrosive',
'Ambrosial Jude',
'My Quiet Romance',
'Flight of the Blond Gerbils',
'Mr Ryan Mai the Salty',
'Scotland Panic',
'Fairyhead',
'The Daring Balloons',
'One Zilliondust',
'Purely Ginger',
'Crazyknot',
'Taking Back October',
'One Zillion Seconds to Scotland',
'The Daring Brains',
'Crazy Fairy Cult',
'Crazy Tooth',
'Bathtub Daring',
'The Crazy Perry Project',
'Fairy One Zillion',
'Disciples Of Scotland',
'Daring Dolls',
'Crazy Crazy Crazy',
'The Crazy Brothers',
'Perry and the Bumpy Humans',
'Letters From Perry of the Elephants',
'Das Fairy',
'Twilight of the Fairy Gods',
'Au Revior Brains']